version: "3"

services:
  app: #d name of the service is "app"
    build: #a section under services where the cmd are configured
      context: . #the scope of the app services is the current dir where it lyes
    ports:
      - "8000:8000"   #port 8000 of the local host is linked to port 8000 of the docker image
    command: > # > symbol makes the code in the next line to connnect wit the current line
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes: #always sync the changes done in app folder in the local host with the app folder inside the docker
      - ./app:/app

